### ISSUE TITLE
Migrate djbr to new structure

### ISSUE THREAD

**Issue by aVolpe** [InstIDEA/controlciudadano#191]
We previously have the `analysis.declarations` table with the data of all declarations, we need to migrate to a new schema where the data comes form two new tables (`staging.djbr_raw_data` and `staging.djbr_downloaded_files`).

This is a epic that will group all the required changes.

# Definition of done

* The portal show info of the new structure in all places

**Comment by aVolpe** [comment]
# ETL

In the ETL's we only have references in the old `contralory_get_pdf` dag that is deprecated.

# Redash

* [ ] https://redash.controlciudadanopy.org/queries/19/source#19
* [ ] https://redash.controlciudadanopy.org/queries/42/source#49
* [ ] https://redash.controlciudadanopy.org/queries/43
* [ ] https://redash.controlciudadanopy.org/queries/49/source#57

# Portal

* [ ] Modal.ts (Affidavit, LocalSearchPersonResult)
* [ ] RedashApi.ts
* [ ] SimpleApi.ts
* [ ] DDJJ.tsx
* [ ] useApi.ts
* [ ] AffidavitList.tsx
* [ ] PersonDetailPage.tsx

# Tables and views

* [ ] analysis.authorities_with_ddjj
* [ ] analysis.full_data

# Api

* There are three usages all in the `ContraloryService.ts` service

**Comment by aVolpe** [comment]
# TODO

* [ ] Create a new table `analysis.djbr`
* [ ] Update tables
* [ ] Update API
* [ ] Update ETL
* [ ] Update Redash
* [ ] Update Portal
